export const regions = [
  "Qoraqalpog'iston",
  "Xorazm viloyati",
  "Navoiy viloyati",
  "Buxoro viloyati",
  "Samarqand viloyati",
  "Qashqadaryo viloyati",
  "Surxondaryo viloyati",
  "Jizzax viloyati",
  "Sirdaryo viloyati",
  "Toshkent viloyati",
  "Namangan viloyati",
  "Farg'ona viloyati",
  "Andijon viloyati",
  "Toshkent shahri",
] as const;

export type Region = (typeof regions)[number];

export const districtsByRegion: Record<Region, string[]> = {
  "Qoraqalpog'iston": [
    "Nukus shahri",
    "Amudaryo tumani",
    "Beruniy tumani",
    "Chimboy tumani",
    "Ellikqal'a tumani",
    "Kegeyli tumani",
    "Mo'ynoq tumani",
    "Qo'ng'irot tumani",
    "Taxiatosh tumani",
    "To'rtko'l tumani",
  ],
  "Xorazm viloyati": [
    "Urganch shahri",
    "Bog'ot tumani",
    "Gurlan tumani",
    "Hazorasp tumani",
    "Xiva tumani",
    "Qo'shko'pir tumani",
    "Shovot tumani",
    "Urganch tumani",
    "Yangiariq tumani",
    "Yangibozor tumani",
  ],
  "Navoiy viloyati": [
    "Navoiy shahri",
    "Zarafshon shahri",
    "Karmana tumani",
    "Konimex tumani",
    "Navbahor tumani",
    "Nurota tumani",
    "Qiziltepa tumani",
    "Tomdi tumani",
    "Uchquduq tumani",
    "Xatirchi tumani",
  ],
  "Buxoro viloyati": [
    "Buxoro shahri",
    "G'ijduvon tumani",
    "Jondor tumani",
    "Kogon tumani",
    "Olot tumani",
    "Peshku tumani",
    "Qorako'l tumani",
    "Romitan tumani",
    "Shofirkon tumani",
    "Vobkent tumani",
  ],
  "Samarqand viloyati": [
    "Samarqand shahri",
    "Bulung'ur tumani",
    "Ishtixon tumani",
    "Jomboy tumani",
    "Kattaqo'rg'on tumani",
    "Narpay tumani",
    "Pastdarg'om tumani",
    "Payariq tumani",
    "Samarqand tumani",
    "Urgut tumani",
  ],
  "Qashqadaryo viloyati": [
    "Qarshi shahri",
    "Chiroqchi tumani",
    "Dehqonobod tumani",
    "G'uzor tumani",
    "Kasbi tumani",
    "Kitob tumani",
    "Koson tumani",
    "Mirishkor tumani",
    "Shahrisabz tumani",
    "Yakkabog' tumani",
  ],
  "Surxondaryo viloyati": [
    "Termiz shahri",
    "Angor tumani",
    "Bandixon tumani",
    "Boysun tumani",
    "Denov tumani",
    "Jarqo'rg'on tumani",
    "Qiziriq tumani",
    "Qumqo'rg'on tumani",
    "Sherobod tumani",
    "Uzun tumani",
  ],
  "Jizzax viloyati": [
    "Jizzax shahri",
    "Arnasoy tumani",
    "Baxmal tumani",
    "Do'stlik tumani",
    "Forish tumani",
    "G'allaorol tumani",
    "Paxtakor tumani",
    "Sharof Rashidov tumani",
    "Zafarobod tumani",
    "Zomin tumani",
  ],
  "Sirdaryo viloyati": [
    "Guliston shahri",
    "Boyovut tumani",
    "Guliston tumani",
    "Mirzaobod tumani",
    "Oqoltin tumani",
    "Sayxunobod tumani",
    "Sardoba tumani",
    "Sirdaryo tumani",
    "Xovos tumani",
    "Yangiyer shahri",
  ],
  "Toshkent viloyati": [
    "Nurafshon shahri",
    "Angren shahri",
    "Bekobod tumani",
    "Bo'stonliq tumani",
    "Chinoz tumani",
    "Ohangaron tumani",
    "Parkent tumani",
    "Qibray tumani",
    "Toshkent tumani",
    "Zangiota tumani",
  ],
  "Namangan viloyati": [
    "Namangan shahri",
    "Chortoq tumani",
    "Chust tumani",
    "Kosonsoy tumani",
    "Mingbuloq tumani",
    "Norin tumani",
    "Pop tumani",
    "To'raqo'rg'on tumani",
    "Uchqo'rg'on tumani",
    "Uychi tumani",
  ],
  "Farg'ona viloyati": [
    "Farg'ona shahri",
    "Qo'qon shahri",
    "Marg'ilon shahri",
    "Beshariq tumani",
    "Bog'dod tumani",
    "Dang'ara tumani",
    "Furqat tumani",
    "Oltiariq tumani",
    "Rishton tumani",
    "Toshloq tumani",
  ],
  "Andijon viloyati": [
    "Andijon shahri",
    "Asaka tumani",
    "Baliqchi tumani",
    "Bo'ston tumani",
    "Buloqboshi tumani",
    "Izboskan tumani",
    "Jalaquduq tumani",
    "Marhamat tumani",
    "Shahrixon tumani",
    "Xo'jaobod tumani",
  ],
  "Toshkent shahri": [
    "Bektemir tumani",
    "Chilonzor tumani",
    "Mirobod tumani",
    "Mirzo Ulug'bek tumani",
    "Olmazor tumani",
    "Sergeli tumani",
    "Shayxontohur tumani",
    "Uchtepa tumani",
    "Yakkasaroy tumani",
    "Yashnobod tumani",
    "Yunusobod tumani",
  ],
};

export function getRegion(value: string): Region | null {
  return regions.find((region) => region === value) ?? null;
}

export function getRegionByIndex(index: number): Region | null {
  return regions[index] ?? null;
}

export function getDistrictByIndex(region: Region, index: number): string | null {
  return districtsByRegion[region][index] ?? null;
}

export function isDistrict(region: Region, value: string): boolean {
  return districtsByRegion[region].includes(value);
}
